### ISSUE TITLE
Missing python module

### ISSUE THREAD

**Issue by delicaed** [Fibbing/FibbingNode#1]
Hi,

The module modified_dijkstra appears to be missing, as I get a traceback when I try to run the demo.py script.

**Comment by oliviertilmans** [comment]
Hello,

I have pushed a fix for this (reference to legacy code ...).
You might be interested in looking at the Fibbing/labs repository to get the IOS configs for that lab.
Drop me a line if you can't get it running!

**Comment by delicaed** [comment]
Thanks very much.
Regards,
Eddie

Sent from my Samsung device

-------- Original message --------
